services:
  app:
    build:
      context: .

    container_name: inventory-management-dev

    env_file:
      - .env

    ports:
      - "${PORT}:5000"

    volumes:
      - .:/home/appuser
      - ./data:/home/appuser/data

    working_dir: /home/appuser

    command:
      - python
      - run.py

  tunnel:
    image: openziti/zrok
    container_name: zrok
    restart: unless-stopped

    depends_on:
      - app
